basePath: /
definitions:
  controllers.DogBreadImages:
    properties:
      message:
        items:
          type: string
        type: array
    type: object
  controllers.DogBreeds:
    properties:
      message:
        additionalProperties: true
        type: object
    type: object
  controllers.ResponseMessage:
    properties:
      message:
        items:
          type: string
        type: array
    type: object
  models.Dogs:
    properties:
      breed:
        type: string
      id:
        type: integer
      name:
        type: string
      sub-breed:
        type: string
    type: object
  models.Response:
    properties:
      message:
        type: string
    type: object
host: localhost:3002
info:
  contact: {}
  description: This is a simple API service for Dog Breeds consume from the Dog API.
  title: API for Dog Breeds
  version: "1.0"
paths:
  /breed/{breed}/images:
    get:
      consumes:
      - application/json
      description: get all breed images
      operationId: get-list-breed-images
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.DogBreadImages'
      summary: Get all breed images
  /breed/{sub-breed}/list:
    get:
      consumes:
      - application/json
      description: get all sub breeds
      operationId: get-list-sub-breeds
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.ResponseMessage'
      summary: Get all sub breeds
  /breeds/list/all:
    get:
      consumes:
      - application/json
      description: get all breeds
      operationId: get-list-breeds
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.DogBreeds'
      summary: Get all breeds
  /dog:
    post:
      consumes:
      - application/json
      description: create a new dog
      operationId: create-dog
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
      summary: Create a new dog
  /dogs:
    get:
      consumes:
      - application/json
      description: get dog list
      operationId: get-dog-list
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Dogs'
            type: array
      summary: Show dog list
  /dogs/{id}:
    delete:
      consumes:
      - application/json
      description: delete a dog
      operationId: delete-dog
      parameters:
      - description: Dog ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
      summary: Delete a dog
    put:
      consumes:
      - application/json
      description: update dog by ID
      operationId: update-dog-by-id
      parameters:
      - description: Dog ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
      summary: Update dog
swagger: "2.0"
